FROM tomcat:8.5.88-jre11-temurin-jammy
LABEL "Project"="devpro"
LABEL "Author"="Ikay"
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/devpro-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
WORKDIR /usr/local/tomcat
VOLUME /usr/local/tomcat/webapps