FROM debian:buster-slim
LABEL "Project"="devpro"
LABEL "Author"="Ikay"

ENV MYSQL_ROOT_PASSWORD= "devprodbpass"
ENV MYSQL_DATABASE= "accounts"

ADD db_backup.sql docker-entrypoint-initdb.d/db_backup.sql


VOLUME /var/lib/mysql

COPY docker-entrypoint.sh /usr/local/bin/
RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat
ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 3306 33060
CMD ["mysqld"]